### ISSUE TITLE
Laravel SPF refreshing pages

### ISSUE THREAD

**Issue by weskshare** [kamrava/laravel-spf#4]
I notice that laravel spf is refreshes a page. I selected common part of the page using my mouse. Then clicked page2 link. It refreshes the page.  In the real spf demo this does not happen. So I wanted to know if this is really spf or am I missing something.

**Comment by kamrava** [comment]
It's exactly what you saw in real spf demo. You missed something.
Can you show me your code?

**Comment by weskshare** [comment]
It wasn't my code, I was just checking your laravel demo. I think its nothing major. Just an error in view on the spf navigate server request.

I am getting "View [pages.page1.partials._title] not found" 500 server error.

I will just follow the documentation and create my own. Thanks for the good work!

**Comment by kamrava** [comment]
You're welcome.
In next release there is no need for separate files like(_head.blade.php etc...)
I will send the PR in next 2 days

**Comment by weskshare** [comment]
Sure . I'll check it out. I fixed the issue temporarily.

I updated render function in SectionView.php and created missing blade files in page1 / page2 folder.

```
public function render()
    {
        $sections = [
            'title' => view($this->path.'.sections._title')->with($this->data)->render(),
            'head'  => view($this->path.'.sections._head' )->with($this->data)->render(),
            'body'  => view($this->path.'.sections._body' )->with($this->data)->render(),
            'foot'  => view($this->path.'.sections._foot' )->with($this->data)->render()
        ];
        $output = $this->addSlashesAndRemoveLines($sections);
        $partials = json_decode(json_encode($output, JSON_FORCE_OBJECT));
        return view($this->path.'.spf_json', ['sections' => $partials]);
    }
```
